### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by shenyanxiang** [1357310795/OfficeInstaller#1]
Couldn't find the specified configuration file. Check the file path and file name.
Error Code: 0-2048(0)
上面是错误信息，安装界面显示的是安装程序启动成功，但返回值非0。
10月初才刚用以前的方法安装了office2021并成功激活，最近几天不知为何突然又要重新激活，下载的激活软件报错跟这个其实是一样的。不知为何要把以前的安装方式删掉，只保留现在这个测试中的一键式呢？

**Comment by 1357310795** [comment]
您好，这是一个已知的BUG，还没来得及更新修复（抱歉，我明天就联系老师）
***

> 不知为何要把以前的安装方式删掉，只保留现在这个测试中的一键式呢？

之前的一键安装脚本和这个工具其实是等效的，但是安装脚本使用起来问题比较多，所以只保留了此工具。至于仅激活的操作，我也觉得应该保留使用命令的形式，我明天再和老师商讨一下

**Comment by 1357310795** [comment]
[OfficeInstaller (1).zip](https://github.com/1357310795/OfficeInstaller/files/9930790/OfficeInstaller.1.zip)

用这个把老版本的 exe 替换掉可以正常使用

**Comment by shenyanxiang** [comment]
替换后出现新的问题了，网络问题导致不能下载需要的文件。连接交大VPN也同样无法解决这个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1357310795/OfficeInstaller"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月3日(星期四) 晚上11:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [1357310795/OfficeInstaller] 安装失败 (Issue #1)





 
OfficeInstaller (1).zip
 
用这个把老版本的 exe 替换掉可以正常使用

**Comment by 1357310795** [comment]
现在是离线版的安装包了…估计你用的仍然是在线版…去 software.sjtu.edu.cn 上再下载一次，然后替换 exe

**Comment by shenyanxiang** [comment]
解决了，谢谢~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月4日(星期五) 上午10:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [1357310795/OfficeInstaller] 安装失败 (Issue #1)





 
现在是离线版的安装包了…估计你用的仍然是在线版…去 software.sjtu.edu.cn 上再下载一次，然后替换 exe
